// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CamMaster.Persistence.Models
{
    public partial class Camera
    {
        public Camera()
        {
            Incidents = new HashSet<Incident>();
            PtzSettings = new HashSet<PtzSetting>();
        }

        public int Id { get; set; }
        public string SerialNumber { get; set; }
        public string Version { get; set; }
        public string Model { get; set; }
        public int? Channel { get; set; }
        public int? Port { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int? UnitId { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public decimal? Memory { get; set; }
        public string Status { get; set; }
        public bool? Microphone { get; set; }

        public virtual Unit Unit { get; set; }
        public virtual ICollection<Incident> Incidents { get; set; }
        public virtual ICollection<PtzSetting> PtzSettings { get; set; }
    }
}