// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CamMaster.Persistence.Models
{
    public partial class CamStationLoginsLog
    {
        public int Id { get; set; }
        public int IdEmployee { get; set; }
        public string Station { get; set; }
        public string Date { get; set; }

        public virtual Employee IdEmployeeNavigation { get; set; }
    }
}