// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CamMaster.Persistence.Models
{
    public partial class CamStationNote
    {
        public int Id { get; set; }
        public string Site { get; set; }
        public string Message { get; set; }
        public int EmployeeId { get; set; }
        public string Date { get; set; }

        public virtual Employee Employee { get; set; }
    }
}