// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CamMaster.Persistence.Models
{
    public partial class CamviewLoginLog
    {
        public int Id { get; set; }
        public int? SiteId { get; set; }
        public string Status { get; set; }
        public string LoginType { get; set; }
        public DateTime? LoginDate { get; set; }
        public string Name { get; set; }

        public virtual Site Site { get; set; }
    }
}