// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CamMaster.Persistence.Models
{
    public partial class ContactProspect
    {
        public int Id { get; set; }
        public int? ContactId { get; set; }
        public int? ProspectId { get; set; }
        public bool? FaceToFace { get; set; }
        public bool? LiveDemonstration { get; set; }
        public bool? Site { get; set; }
        public string Typee { get; set; }

        public virtual Contact Contact { get; set; }
        public virtual Prospect Prospect { get; set; }
    }
}