// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CamMaster.Persistence.Models
{
    public partial class Contact
    {
        public Contact()
        {
            ContactNotes = new HashSet<ContactNote>();
            ContactProspects = new HashSet<ContactProspect>();
            ContactSites = new HashSet<ContactSite>();
            Telephones = new HashSet<Telephone>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Position { get; set; }
        public string Email { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public string LastName { get; set; }
        public string Nickname { get; set; }
        public string Type { get; set; }

        public virtual ICollection<ContactNote> ContactNotes { get; set; }
        public virtual ICollection<ContactProspect> ContactProspects { get; set; }
        public virtual ICollection<ContactSite> ContactSites { get; set; }
        public virtual ICollection<Telephone> Telephones { get; set; }
    }
}