// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CamMaster.Persistence.Models
{
    public partial class Employee
    {
        public Employee()
        {
            CamStationLoginsLogs = new HashSet<CamStationLoginsLog>();
            CamStationNotes = new HashSet<CamStationNote>();
            FingerprintTemplates = new HashSet<FingerprintTemplate>();
            IncidentMonitoristNavigations = new HashSet<Incident>();
            IncidentSupervisorNavigations = new HashSet<Incident>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int? AuthorizationLevel { get; set; }
        public int? DepartmentId { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }

        public virtual Department Department { get; set; }
        public virtual ICollection<CamStationLoginsLog> CamStationLoginsLogs { get; set; }
        public virtual ICollection<CamStationNote> CamStationNotes { get; set; }
        public virtual ICollection<FingerprintTemplate> FingerprintTemplates { get; set; }
        public virtual ICollection<Incident> IncidentMonitoristNavigations { get; set; }
        public virtual ICollection<Incident> IncidentSupervisorNavigations { get; set; }
    }
}