// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CamMaster.Persistence.Models
{
    public partial class FingerprintTemplate
    {
        public int Id { get; set; }
        public string Image1Base64 { get; set; }
        public string Image2Base64 { get; set; }
        public string Image3Base64 { get; set; }
        public int EmployeeId { get; set; }

        public virtual Employee Employee { get; set; }
    }
}