// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CamMaster.Persistence.Models
{
    public partial class Incident
    {
        public long Id { get; set; }
        public string Message { get; set; }
        public int CameraId { get; set; }
        public int ZoneId { get; set; }
        public int CreatedByMonitorId { get; set; }
        public DateTimeOffset CreatedAt { get; set; }
        public int? AssignedToSupervisorId { get; set; }
        public DateTimeOffset? AssignedAt { get; set; }
        public int? CompletedBySupervisorId { get; set; }
        public DateTimeOffset? CompletedAt { get; set; }
        public bool? Expired { get; set; }
        public DateTimeOffset? ExpiredAt { get; set; }
        public int AssignmentId { get; set; }
        public string HostName { get; set; }
    }
}