// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CamMaster.Persistence.Models
{
    public partial class Industry
    {
        public Industry()
        {
            DecisionMakerRoles = new HashSet<DecisionMakerRole>();
            Leads = new HashSet<Lead>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }

        public virtual ICollection<DecisionMakerRole> DecisionMakerRoles { get; set; }
        public virtual ICollection<Lead> Leads { get; set; }
    }
}