// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CamMaster.Persistence.Models
{
    public partial class Lead
    {
        public Lead()
        {
            Clients = new HashSet<Client>();
            FaceToFaces = new HashSet<FaceToFace>();
            LiveDemonstrations = new HashSet<LiveDemonstration>();
            Proposals = new HashSet<Proposal>();
            Prospects = new HashSet<Prospect>();
            Sites = new HashSet<Site>();
        }

        public int Id { get; set; }
        public int? CompanyId { get; set; }
        public string Project { get; set; }
        public int IndustryId { get; set; }
        public int? ReferralId { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public int? UserId { get; set; }
        public string Notes { get; set; }

        public virtual Company Company { get; set; }
        public virtual Industry Industry { get; set; }
        public virtual Referral Referral { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Client> Clients { get; set; }
        public virtual ICollection<FaceToFace> FaceToFaces { get; set; }
        public virtual ICollection<LiveDemonstration> LiveDemonstrations { get; set; }
        public virtual ICollection<Proposal> Proposals { get; set; }
        public virtual ICollection<Prospect> Prospects { get; set; }
        public virtual ICollection<Site> Sites { get; set; }
    }
}