// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CamMaster.Persistence.Models
{
    public partial class MaintenanceSolarPanel
    {
        public int Id { get; set; }
        public bool? PanelStatus { get; set; }
        public bool? SunsaverStatus { get; set; }
        public bool? BatteryStatus { get; set; }
        public string DatailsSolarPanel { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public int? SolarPanelId { get; set; }

        public virtual SolarPanel SolarPanel { get; set; }
    }
}