// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CamMaster.Persistence.Models
{
    public partial class Nvr
    {
        public Nvr()
        {
            SimCards = new HashSet<SimCard>();
        }

        public int Id { get; set; }
        public string SerialNumber { get; set; }
        public string Name { get; set; }
        public string Ip { get; set; }
        public int? Port { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Version { get; set; }
        public int? Channels { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }

        public virtual ICollection<SimCard> SimCards { get; set; }
    }
}