// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CamMaster.Persistence.Models
{
    public partial class Password
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public string Password1 { get; set; }
        public int? SiteId { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }

        public virtual Site Site { get; set; }
    }
}