// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CamMaster.Persistence.Models
{
    public partial class Proposal
    {
        public Proposal()
        {
            ProposalUnits = new HashSet<ProposalUnit>();
        }

        public int Id { get; set; }
        public int? LeadId { get; set; }
        public string MonitoringCategory { get; set; }
        public string Notes { get; set; }
        public decimal? SetupFee { get; set; }
        public decimal? PurchaseTotal { get; set; }
        public decimal? Lease { get; set; }
        public decimal? Monitoring { get; set; }
        public decimal? MonthlySubtotal { get; set; }
        public decimal? MonthlyDiscount { get; set; }
        public decimal? MonthlyTotal { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public int? UserId { get; set; }
        public decimal? SpecialDiscount { get; set; }

        public virtual Lead Lead { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<ProposalUnit> ProposalUnits { get; set; }
    }
}