// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CamMaster.Persistence.Models
{
    public partial class ProposalUnit
    {
        public ProposalUnit()
        {
            C1Files = new HashSet<C1File>();
            C2Files = new HashSet<C2File>();
            C3Files = new HashSet<C3File>();
        }

        public int Id { get; set; }
        public decimal? Latitude { get; set; }
        public decimal? Longitude { get; set; }
        public string SolarPanel { get; set; }
        public string Lease { get; set; }
        public string Type { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public int ProposalId { get; set; }

        public virtual Proposal Proposal { get; set; }
        public virtual ICollection<C1File> C1Files { get; set; }
        public virtual ICollection<C2File> C2Files { get; set; }
        public virtual ICollection<C3File> C3Files { get; set; }
    }
}