// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CamMaster.Persistence.Models
{
    public partial class Prospect
    {
        public Prospect()
        {
            ContactProspects = new HashSet<ContactProspect>();
        }

        public int Id { get; set; }
        public decimal? SiteLatitude { get; set; }
        public decimal? SiteLongitude { get; set; }
        public string SiteAddress { get; set; }
        public string SiteCity { get; set; }
        public string SiteState { get; set; }
        public string SiteZipCode { get; set; }
        public string DmAddress { get; set; }
        public string DmCity { get; set; }
        public string DmState { get; set; }
        public string DmZipCode { get; set; }
        public string SiteCountry { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public int LeadId { get; set; }
        public int? UserId { get; set; }
        public string DmCountry { get; set; }
        public string Notes { get; set; }

        public virtual Lead Lead { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<ContactProspect> ContactProspects { get; set; }
    }
}