// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CamMaster.Persistence.Models
{
    public partial class SimCard
    {
        public int Id { get; set; }
        public string SerialNumber { get; set; }
        public string Ip { get; set; }
        public string Provider { get; set; }
        public string Apn { get; set; }
        public string Phone { get; set; }
        public int? NvrId { get; set; }
        public int? UnitId { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }

        public virtual Nvr Nvr { get; set; }
        public virtual Unit Unit { get; set; }
    }
}