// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CamMaster.Persistence.Models
{
    public partial class Site
    {
        public Site()
        {
            CamviewLoginLogs = new HashSet<CamviewLoginLog>();
            ContactSites = new HashSet<ContactSite>();
            Passwords = new HashSet<Password>();
            Units = new HashSet<Unit>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Details { get; set; }
        public string MonitoringSchedule { get; set; }
        public string Username { get; set; }
        public string Status { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public int? LeadId { get; set; }
        public int? PoliceDepartmentId { get; set; }

        public virtual Lead Lead { get; set; }
        public virtual PoliceDepartment PoliceDepartment { get; set; }
        public virtual ICollection<CamviewLoginLog> CamviewLoginLogs { get; set; }
        public virtual ICollection<ContactSite> ContactSites { get; set; }
        public virtual ICollection<Password> Passwords { get; set; }
        public virtual ICollection<Unit> Units { get; set; }
    }
}