// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CamMaster.Persistence.Models
{
    public partial class SolarPanel
    {
        public SolarPanel()
        {
            MaintenanceSolarPanels = new HashSet<MaintenanceSolarPanel>();
            SolarPanelFiles = new HashSet<SolarPanelFile>();
        }

        public int Id { get; set; }
        public string SerialNumber { get; set; }
        public string Company { get; set; }
        public decimal? Capacity { get; set; }
        public string Status { get; set; }
        public string Notes { get; set; }
        public int? UnitId { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public string CountryOrigin { get; set; }
        public DateTime? Battery1Date { get; set; }
        public string Battery1Serial { get; set; }
        public DateTime? Battery2Date { get; set; }
        public string Battery2Serial { get; set; }
        public string SunsaverModel { get; set; }
        public string SunsaverSerial { get; set; }

        public virtual Unit Unit { get; set; }
        public virtual ICollection<MaintenanceSolarPanel> MaintenanceSolarPanels { get; set; }
        public virtual ICollection<SolarPanelFile> SolarPanelFiles { get; set; }
    }
}