// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CamMaster.Persistence.Models
{
    public partial class SupervisorCamera
    {
        public int Id { get; set; }
        public string NvrIp { get; set; }
        public int? ChannelCamera { get; set; }
        public string SeenSupervisor { get; set; }
        public string Reason { get; set; }
        public string SendSupervisor { get; set; }
        public string Date { get; set; }
        public int? IdEmployee { get; set; }
        public int? IncidentId { get; set; }
        public int? Supervisor { get; set; }
        public short? Zone { get; set; }
    }
}