// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CamMaster.Persistence.Models
{
    public partial class Telephone
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public string Number { get; set; }
        public int? ContactId { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public string CountryCode { get; set; }
        public string Extension { get; set; }

        public virtual Contact Contact { get; set; }
    }
}