// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CamMaster.Persistence.Models
{
    public partial class Unit
    {
        public Unit()
        {
            AirCards = new HashSet<AirCard>();
            Cameras = new HashSet<Camera>();
            MaintenanceUnits = new HashSet<MaintenanceUnit>();
            PresetPtzs = new HashSet<PresetPtz>();
            Routers = new HashSet<Router>();
            SimCards = new HashSet<SimCard>();
            SolarPanels = new HashSet<SolarPanel>();
            StationUnits = new HashSet<StationUnit>();
            UnitFiles = new HashSet<UnitFile>();
            UnitLocations = new HashSet<UnitLocation>();
            VoltageLogs = new HashSet<VoltageLog>();
        }

        public int Id { get; set; }
        public string SerialNumber { get; set; }
        public string Type { get; set; }
        public string Details { get; set; }
        public string Status { get; set; }
        public int? SiteId { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public string ArduinoVersion { get; set; }
        public string LocationDescription { get; set; }

        public virtual Site Site { get; set; }
        public virtual ICollection<AirCard> AirCards { get; set; }
        public virtual ICollection<Camera> Cameras { get; set; }
        public virtual ICollection<MaintenanceUnit> MaintenanceUnits { get; set; }
        public virtual ICollection<PresetPtz> PresetPtzs { get; set; }
        public virtual ICollection<Router> Routers { get; set; }
        public virtual ICollection<SimCard> SimCards { get; set; }
        public virtual ICollection<SolarPanel> SolarPanels { get; set; }
        public virtual ICollection<StationUnit> StationUnits { get; set; }
        public virtual ICollection<UnitFile> UnitFiles { get; set; }
        public virtual ICollection<UnitLocation> UnitLocations { get; set; }
        public virtual ICollection<VoltageLog> VoltageLogs { get; set; }
    }
}