// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CamMaster.Persistence.Models
{
    public partial class User
    {
        public User()
        {
            ContactNotes = new HashSet<ContactNote>();
            FaceToFaces = new HashSet<FaceToFace>();
            Leads = new HashSet<Lead>();
            LiveDemonstrations = new HashSet<LiveDemonstration>();
            Proposals = new HashSet<Proposal>();
            Prospects = new HashSet<Prospect>();
            RoleUsers = new HashSet<RoleUser>();
            Updates = new HashSet<Update>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string RememberToken { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public string LastName { get; set; }
        public bool? Active { get; set; }

        public virtual ICollection<ContactNote> ContactNotes { get; set; }
        public virtual ICollection<FaceToFace> FaceToFaces { get; set; }
        public virtual ICollection<Lead> Leads { get; set; }
        public virtual ICollection<LiveDemonstration> LiveDemonstrations { get; set; }
        public virtual ICollection<Proposal> Proposals { get; set; }
        public virtual ICollection<Prospect> Prospects { get; set; }
        public virtual ICollection<RoleUser> RoleUsers { get; set; }
        public virtual ICollection<Update> Updates { get; set; }
    }
}